### ISSUE TITLE
Corruption of entire .blend file if Save is done when cursor is on top of Object Panel

### ISSUE THREAD

**Issue by franklinblanco** [kaosat-dev/Blenvy#103] opened 2024-01-22 13:27 UTC
DETAILS:
OS: MAC OSX SONOMA 14.2.1
Blender: Blender 4.0
Hardware: M1 Mac Pro 32GB Ram 1TB Storage (2021) Base config

Hello. Just wanted to thank you all for the great work. This library is amazing.

Currently, I'm having a big issue, I setup the GLTF_AUTO_EXPORT plugin in blender and it works great. But whenever I place my cursor anywhere near the Custom Properties Option in the Object Panel I get an error and the whole .blend file gets corrupted.

Normal Blender file with gltf_auto_export_setup
![Screenshot 2024-01-22 at 2 28 16 PM](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/72827992/8c34ed39-0bca-43ab-bd11-209b33988964)

GLTF_AUTO_EXPORT configuration
![Screenshot 2024-01-22 at 2 22 02 PM](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/72827992/dda84759-566c-4ae7-9b32-20c7f843c0f9)

This is what happens when you hit save with your cursor on top of the panel
![Screenshot 2024-01-22 at 2 28 45 PM](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/72827992/721f2f6b-bb2e-4ea8-87b5-198cc19a1d79)

In green is where having your cursor is safe to save, in red is where it corrupts everything
![Screenshot 2024-01-22 at 2 22 27 PM](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/72827992/c890d663-bb28-4867-a14e-fd48a9e3cd8d)

**Comment by czettnersandor** [comment] 2024-01-22 13:45
Ah, I could not find the exact cause of this error, for me, it seemed completely random, but I can confirm it's when the mouse is over the object panel. BTW the file is not corrupted, you can delete the temp_scene (X icon on the top right near the scene name) and get back your objects on screen.

**Comment by franklinblanco** [comment] 2024-01-22 13:48
@czettnersandor I tried doing that but look at the custom properties (they get blanked) and names of things like the collection:
![Screenshot 2024-01-22 at 2 47 55 PM](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/72827992/04586f53-965c-4b0f-af3b-a687fc3ea952)

**Comment by franklinblanco** [comment] 2024-01-22 16:27
@kaosat-dev So, as for Undo, it doesn't do anything for me. It's like the whole Undo Tree gets deleted. 
For some reason after it happened a few times it just started happening everywhere in some blender files. Didn't really spend time replicating it but I found that switching to v0.9 of the plugin didn't have any of these issues. So for now I'm sticking to that version. Wish I had an interest in python so I could help out. But all python just gives me a fat headache.

**Comment by kaosat-dev** [comment] 2024-01-23 23:44
> @kaosat-dev So, as for Undo, it doesn't do anything for me. It's like the whole Undo Tree gets deleted. 
> For some reason after it happened a few times it just started happening everywhere in some blender files. Didn't really spend time replicating it but I found that switching to v0.9 of the plugin didn't have any of these issues. So for now I'm sticking to that version. Wish I had an interest in python so I could help out. But all python just gives me a fat headache.
> 
> 

Thanks for the report about it working in v0.9 ! I have a few ideas about the regression.
Also precious information about undo.
No worries, my brain seems about to explode switching between python and Rust so I can understand 😅
I will tackle these issues once I am done with the UI tool PR (giant PR !), hope that is ok.

**Comment by kaosat-dev** [comment] 2024-01-31 13:55
Hi  @franklinblanco & @czettnersandor 
I just spent quite a bit of time trying to solve this issue (decided to get it fixed before the big new release).
And I am baffled, some Blender things that are supposed to be reliable seem to break just based on the cursor position,  some data structures that are normally present and filled get empty , just because of the placement of the cursor o_O, quite maddening.
I am still investigating, but I am leaning more and more towards an issue with Blender itself. 

@franklinblanco are you 100% sure that the issue was not present in v0.9 ? because the impacted parts, as far as I can tell where already present in that version (though the actual error would be different in that version, but still fail)

**Comment by franklinblanco** [comment] 2024-01-31 14:17
@kaosat-dev Hello! Once again thank you for taking precious time out for this. So I used the 0.9 version for quite a while now and at the start it was not happening based on cursor position, but the days have passed and now I've found that yes it still happend in 0.9. Looks to me like a blender thing yes. 


By the way, just wanted to say, after using this plugin for a while... It's helped me incredibly through the development of my game. I'm always very wary of using things I didn't write myself, at the start I completely avoided the auto save plugin and the blueprints part of your plugin, and I got to say boy was I wrong for doing that, now It just works smooth and perfectly. I'll be making some devlogs soon and I'll make sure to shout out this plugin every chance I get. Thank you. Anything else you need let me know.

**Comment by kaosat-dev** [comment] 2024-02-05 08:43
Hi again @franklinblanco !
Thanks for confirming that it was also present in v0.9. 
I ended up rewriting a significant portion of the exporter to try and get around the problem (I created a PR on the Blender Gltf exporter repo as well, hope it can get merged for Blender 4.1), so hopefully that issue (and many others) should be fixed in v0.11 (preparing the release right now).

And thank your for the very kind words ! Very happy that the tooling has helped you so far :) Looking forward to reading your devlogs ! The more feedback , the more I can fine tune things and make the tooling better ;)

**Closed as completed** 2024-02-05 08:49 UTC
